config/routes.rb
Rails.application.routes.draw do
  resources :stalls

  root 'static#index'

end

app/models/stall.rb
class Stall < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/stalls_controller.rb
class StallsController < ApplicationController
  before_action :set_stall, only: [:show, :edit, :update, :destroy]

  # GET /stalls
  # GET /stalls.json
  def index
    @stalls = Stall.all
  end

  # GET /stalls/1
  # GET /stalls/1.json
  def show
  end

  # GET /stalls/new
  def new
    @stall = Stall.new
  end

  # GET /stalls/1/edit
  def edit
  end

  # POST /stalls
  # POST /stalls.json
  def create
    @stall = Stall.new(stall_params)

    respond_to do |format|
      if @stall.save
        format.html { redirect_to @stall, notice: 'Stall was successfully created.' }
        format.json { render :show, status: :created, location: @stall }
      else
        format.html { render :new }
        format.json { render json: @stall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stalls/1
  # PATCH/PUT /stalls/1.json
  def update
    respond_to do |format|
      if @stall.update(stall_params)
        format.html { redirect_to @stall, notice: 'Stall was successfully updated.' }
        format.json { render :show, status: :ok, location: @stall }
      else
        format.html { render :edit }
        format.json { render json: @stall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stalls/1
  # DELETE /stalls/1.json
  def destroy
    @stall.destroy
    respond_to do |format|
      format.html { redirect_to stalls_url, notice: 'Stall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stall
      @stall = Stall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stall_params
      params.require(:stall).permit(:name, :price, :description)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stalls_helper.rb
module StallsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="leatherLaneMarketApp">
<head>
  <title>StallsRailsAngular</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stalls/_form.html.erb
<%= form_for(@stall) do |f| %>
  <% if @stall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stall.errors.count, "error") %> prohibited this stall from being saved:</h2>

      <ul>
      <% @stall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stalls/edit.html.erb
<h1>Editing stall</h1>

<%= render 'form' %>

<%= link_to 'Show', @stall %> |
<%= link_to 'Back', stalls_path %>

app/views/stalls/index.html.erb
<h1>Listing stalls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stalls.each do |stall| %>
      <tr>
        <td><%= stall.name %></td>
        <td><%= stall.price %></td>
        <td><%= stall.description %></td>
        <td><%= link_to 'Show', stall %></td>
        <td><%= link_to 'Edit', edit_stall_path(stall) %></td>
        <td><%= link_to 'Destroy', stall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stall', new_stall_path %>

app/views/stalls/new.html.erb
<h1>New stall</h1>

<%= render 'form' %>

<%= link_to 'Back', stalls_path %>

app/views/stalls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stall.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @stall.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @stall.description %>
</p>

<%= link_to 'Edit', edit_stall_path(@stall) %> |
<%= link_to 'Back', stalls_path %>